# Generated by Django 3.0.6 on 2021-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passwors',
            field=models.TextField(),
        ),
    ]
